export const coffee = [
    {
        id: 1,
        title: "Classic Brew",
        description: "A traditional and rich coffee blend that never disappoints.",
        image: "https://transform.nws.ai/https%3A//cdn.thenewsroom.io/platform/story_media/1288819281/542212056.jpg/w_1200,c_limit/",
        bestSeller: false,
      },
      {
        id: 2,
        title: "Espresso Shot",
        description: "An intense and bold espresso shot for the coffee purists.",
        image: "https://images.unsplash.com/photo-1601390483714-955fd3066695?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8ZXNwcmVzc28lMjBzaG90fGVufDB8fDB8fHww&w=1000&q=80",
        bestSeller: true,
      },
      {
        id: 3,
        title: "Caramel Macchiato",
        description: "A delightful mix of espresso, steamed milk, and caramel syrup.",
        image: "https://cooktoria.com/wp-content/uploads/2016/02/Caramel-Macchiato-Recipe-sq-1.jpg",
        bestSeller: true,
      },
      {
        id: 4,
        title: "Mocha Latte",
        description: "An indulgent blend of espresso, steamed milk, and chocolate.",
        image: "https://milkandpop.com/wp-content/uploads/2020/11/mocha-latte-13-720x540.jpg",
        bestSeller: false,
      },
      {
        id: 5,
        title: "Vanilla Frappe",
        description: "A sweet and creamy coffee frappe with a hint of vanilla.",
        image: "https://azestybite.com/wp-content/uploads/2014/08/Vanilla-Ice-Coffee-Frappe-480x480.jpg",
        bestSeller: false,
      },
      {
        id: 6,
        title: "Iced Americano",
        description: "A refreshing iced coffee with a double shot of espresso.",
        image: "https://images.ctfassets.net/v601h1fyjgba/1vlXSpBbgUo9yLzh71tnOT/a1afdbe54a383d064576b5e628035f04/Iced_Americano.jpg",
        bestSeller: true,
      },
      {
        id: 7,
        title: "Cappuccino",
        description: "A classic Italian coffee with equal parts espresso, steamed milk, and foam.",
        image: "https://images.unsplash.com/photo-1572442388796-11668a67e53d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8Y2FwcHVjY2lubyUyMGNvZmZlZXxlbnwwfHwwfHx8MA%3D%3D&w=1000&q=80",
        bestSeller: true,
      },
      {
        id: 8,
        title: "Hazelnut Delight",
        description: "A delightful blend of espresso, hazelnut syrup, and frothy milk.",
        image: "https://lh3.googleusercontent.com/fSWp0dSg2jXDCwOwsOuZJPH3ESfoD7bH3cUL0lsw3JlAE5hth0S_GQxTlErmqc3E-_rXc7Hq061_IXQc05Mfv60498VxxBaOxlIV5J8X=w512-rw",
        bestSeller: false,
      },
      {
        id: 9,
        title: "Cinnamon Swirl",
        description: "A warm and comforting coffee with a dash of cinnamon.",
        image: "https://img.freepik.com/premium-photo/cup-coffee-with-cinnamon-swirl-rim_900958-37504.jpg",
        bestSeller: false,
      },
      {
        id: 10,
        title: "Cold Brew",
        description: "A smooth and strong coffee brewed with cold water.",
        image: "https://www.simplejoy.com/wp-content/uploads/2021/09/cold-brew-coffee.jpg",
        bestSeller: true,
      },
      {
        id: 11,
        title: "Iced Caramel Latte",
        description: "A refreshing iced coffee with caramel syrup and milk.",
        image: "https://mocktail.net/wp-content/uploads/2022/06/Iced-Caramel-Latte_4-ig.jpg",
        bestSeller: false,
      },
      {
        id: 12,
        title: "Decaf Delight",
        description: "A decaffeinated coffee blend that doesn't compromise on flavor.",
        image: "https://cdn.shopify.com/s/files/1/0838/4525/files/hazelnut-coffee_1024x1024.jpg?v=1672677872",
        bestSeller: false,
      },
      {
        id: 13,
        title: "Flat White",
        description: "A velvety smooth coffee with espresso and steamed milk.",
        image: "https://static.toiimg.com/thumb/86699095.cms?width=1200&height=900",
        bestSeller: true,
      },
      {
        id: 14,
        title: "Mint Mocha",
        description: "An invigorating blend of espresso, chocolate, and mint.",
        image: "https://www.itstea.co.uk/wp-content/uploads/2022/03/mintmocha-copy-scaled.jpg",
        bestSeller: false,
      },
      {
        id: 15,
        title: "Iced Vanilla Latte",
        description: "A refreshing iced coffee with vanilla syrup and milk.",
        image: "https://www.whiskaffair.com/wp-content/uploads/2020/12/Iced-Vanilla-Latte-2-3.jpg",
        bestSeller: true,
      },
      {
        id: 16,
        title: "Toffee Crunch",
        description: "A delightful blend of espresso, toffee syrup, and steamed milk.",
        image: "https://media1.popsugar-assets.com/files/thumbor/qMKS4XUiByonwhn9JixbtkuzMzA/fit-in/2048xorig/filters:format_auto-!!-:strip_icc-!!-/2019/11/05/656/n/42718227/4376f5702770bd7b_Iced_Toffee_Nut_Latte/i/Iced-Toffee-Nut-Latte.jpg",
        bestSeller: false,
      },
      {
        id: 17,
        title: "Affogato",
        description: "A simple yet indulgent dessert of espresso poured over vanilla ice cream.",
        image: "https://www.thespruceeats.com/thmb/5PcCBEaUd1U1eFxfcKKPLVnZzfA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/affogato-4776668-hero-08-40d7a68d12ba46f48eaea3c43aba715c.jpg",
        bestSeller: false,
      },
      {
        id: 18,
        title: "Caramel Cappuccino",
        description: "A caramel twist on the classic cappuccino.",
        image: "https://media.istockphoto.com/id/475734036/photo/cup-of-caramel-cappuccino-coffee.jpg?s=612x612&w=0&k=20&c=AzWB_G-fiIkQxtkX2qiQkOJcXVIrJ-pLOACUMIYuynk=",
        bestSeller: false,
      },
      {
        id: 19,
        title: "Pumpkin Spice Latte",
        description: "A seasonal favorite with pumpkin spice flavors and espresso.",
        image: "https://images.aws.nestle.recipes/original/66a50206d704754c115305a2247070ee_bak---21---libby_s-pumpkin-spice-latte-1562-edit.jpg",
        bestSeller: true,
      },
      {
        id: 20,
        title: "Iced Mocha",
        description: "A refreshing blend of espresso, chocolate, and cold milk.",
        image: "https://bakingmischief.com/wp-content/uploads/2019/05/iced-mocha-image-square.jpg",
        bestSeller: false,
      },
]